services:
  valheim-server:
    image: ghcr.io/teriyakidactyl/docker-valheim-server:latest
    container_name: valheim-server
    restart: unless-stopped
    stop_grace_period: 45s
    environment:
      SERVER_NAME: ${SERVER_NAME:-MyValheimServer}
      WORLD_NAME: ${WORLD_NAME:-Teriyakolypse}
      SERVER_PASS: ${SERVER_PASS:-MySecretPassword}
      SERVER_PUBLIC: ${SERVER_PUBLIC:-0}
      SERVER_PORT: ${SERVER_PORT:-2456}
      STEAM_ID_ALLOW_LIST: ${STEAM_ID_ALLOW_LIST:-}
      STEAM_VALIDATE: ${STEAM_VALIDATE:-false}
      UPDATE_ON_START: ${UPDATE_ON_START:-true}
    volumes:
      - valheim_world:/world
      - valheim_app:/app
    ports:
      - "${SERVER_PORT:-2456}:${SERVER_PORT:-2456}/udp"
      - "${SERVER_QUERY_PORT:-2457}:${SERVER_QUERY_PORT:-2457}/udp"

volumes:
  valheim_world:
    name: valheim_world
  valheim_app:
    name: valheim_app
